hugoblox:
  schema: "2.0"
  identity:
    name: Leah Houseman
    logo: ""
    type: person
    tagline: PhD Student & Programs Officer | USask
    organization: University of Saskatchewan
    description: Exploring disability, adulthood transitions, and social determinants through data-driven insights and policy-focused analytics.
    pro: 
      hide_attribution: true
  #Theme and layout
  theme:
    mode: system
    pack: dracula
    colors:
      primary: "36451E"
      secondary: "#36451E"
      neutral: ""
    colors_light:
      primary: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: square
  pro:
    hide_attribution: true
  copyright:
    notice: © {year}, {name}, {license}
  footer:
    text: Leah Houseman | leah.houseman@usask.ca | 2026

# Localization
locale:
  date_format: "Jan 2, 2006"
  time_format: "3:04 PM"

  #Header
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true

  #Footer
  footer:
    style: minimal
    text: "Leah Houseman 2026"
    language_switcher: true
    pro:
      hide_attribution: true

  #Copyright
  copyright:
    notice: © {year} {name}

  #Site features
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true

# Security
security:
  allow_frame: true
