hugoblox:
  schema: "2.0"
  identity:
    name: Leah Houseman
    type: person
    tagline: PhD Student & Programs Officer | USask
    description: ""

  #Theme and layout
  theme:
    mode: system
    pack: dracula
    colors:
      primary: ""
      secondary: ""
      neutral: ""
    colors_light:
      primary: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle

# Localization
locale:
  date_format: "Jan 2, 2006"
  time_format: "3:04 PM"

  #Header
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true

  #Footer
  footer:
    style: minimal
    text: "Leah Houseman 2026"
    language_switcher: true
    attribution: false

  #Copyright
  copyright:
    notice: Â© {year} {name}

  #Site features
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true

# Security
security:
  allow_frame: true
